sudo: required

language: java

env: 
  - DOCKER_COMPOSE_VERSION=1.18.0

services:
  - docker

before_install:
  - mvn clean package
  - docker build -t dgaspi/studis-jdbc .
  - docker tag dgaspi/studis-jdbc dgaspi/studis-jdbc 

dist: trusty

jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.m2"
install: mvn clean install -DskipTests=true -V -U
script: 
  - mvn test
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
